export const browserCopy = {
  featureName: "浏览器操作",
  start: "开启浏览器操作",
  startConfirmTitle: "允许 AI 操作浏览器？",
  startConfirmBody:
    "开启后会打开一个自动化浏览器窗口，AI 在其中帮你完成网页任务。提交、下单等关键操作会先征求你同意，你也可随时点「停止」。",
  stop: "停止",
  stopped: "已停止浏览器操作",
  started: "已开启浏览器操作",
  startFailed: "无法开启浏览器操作",
  loginHintTitle: "先登录你常用的网站",
  loginHintBody:
    "浏览器窗口打开后，在里面登录一次，登录状态会被记住，下次无需重登。",
  headlessHint: "静默模式已开启：不会弹出浏览器窗口，AI 在后台浏览。建议仅用于抓取/检索。",
  noChromeTitle: "未检测到 Chrome 浏览器",
  noChromeBody: "浏览器操作需要本机安装 Chrome。请安装 Chrome 后点「重新检测」。",
  recheck: "重新检测",
  emptyTitle: "尚未有浏览器操作",
  emptyHint: "浏览器已就绪，AI 需要时会自动打开网页并操作，过程会实时显示在这里。",
  loading: "正在准备浏览器…",
  errorTitle: "浏览器操作出错",
  retry: "重试",
  stepOpen: "打开网页", stepLook: "查看页面", stepClick: "点击",
  stepFill: "填写", stepSelect: "选择", stepScroll: "滚动",
  stepExtract: "提取内容", stepWait: "等待", stepBack: "返回",
  openBrowser: "打开浏览器",
  openingBrowser: "正在打开浏览器…",
  closeBrowser: "关闭浏览器",
  closedBrowser: "已关闭浏览器",
  closeBrowserHint: "浏览器会一直开着供后续任务复用；不需要时可手动关闭。",
} as const;
