/** 资料库模块用户面文案（单一文案源，禁用技术词）。 */
export const KB_COPY = {
  navLabel: "资料库",
  pageTitle: "资料库",
  pageSubtitle: "添加资料，让助手在对话中查阅引用。",
  newButton: "新建资料库",
  empty: { title: "还没有资料库", desc: "创建第一个资料库，把常用文档、网页或笔记添加进来，助手就能在对话里查阅它们。" },
  loadFailed: "加载资料库失败",
  retry: "重试",
  createFailed: "创建失败",
  deleteFailed: "删除失败",
  deleteConfirm: (name: string) => ({
    title: "删除资料库",
    message: `确定删除「${name}」吗？库内资料会一并清除，此操作不可撤销。`,
  }),
  created: "已创建",
  deleted: "已删除",
  docCountUnit: "份资料",
  // 新建弹窗
  createTitle: "新建资料库",
  createDesc: "起个好记的名字，之后往里添加资料。",
  nameLabel: "名称",
  namePlaceholder: "例如：产品文档、行业研报",
  cancel: "取消",
  create: "创建",
  creating: "创建中…",
} as const;

export const KB_DETAIL_COPY = {
  back: "资料库",
  // 头部操作
  addResource: "添加资料",
  buildIndex: "增强检索",
  building: "增强中…",
  buildIndexDone: (n: number) => (n > 0 ? `已增强 ${n} 个片段的检索` : "没有需要增强的片段"),
  buildIndexFailed: "增强检索失败",
  // 资料列表
  docsTitle: "资料",
  emptyDocs: { title: "还没有资料", desc: "点右上角「添加资料」，可以粘贴文本、选择本地文件或抓取网页。" },
  loadDocsFailed: "加载资料失败",
  retry: "重试",
  charUnit: "字",
  deleteDocConfirm: (t: string) => ({ title: "删除资料", message: `确定删除「${t}」吗？` }),
  docDeleted: "已删除",
  statusText: (s: string) =>
    s === "ready" ? "可用" : s === "error" ? "解析失败" : s === "parsing" ? "处理中" : "待处理",
  // 添加资料弹窗
  addTitle: "添加资料",
  addDesc: "支持粘贴文本、本地文件（md/txt/pdf/docx/pptx/xlsx）或网页地址。",
  tabPaste: "粘贴文本",
  tabFile: "本地文件",
  tabUrl: "网页",
  titleLabel: "标题",
  titlePlaceholder: "给这份资料起个标题（选填）",
  pastePlaceholder: "把要添加的内容粘贴到这里…",
  addByPaste: "添加",
  adding: "添加中…",
  pickFile: "选择文件",
  pickAnother: "重新选择",
  fileHint: "支持 md / txt / pdf / docx / pptx / xlsx",
  urlPlaceholder: "https://…",
  urlHint: "将抓取网页正文并添加为一份资料。",
  urlAdd: "抓取并添加",
  addFailed: "添加失败",
  added: "已添加资料",
  cancel: "取消",
  // 查看资料内容
  view: "查看",
  viewLoading: "加载内容中…",
  viewEmpty: "这份资料没有可显示的内容（可能解析失败或尚未处理）。",
  // 查阅预览（抽屉）
  preview: "查阅",
  previewTitle: "查阅预览",
  previewDesc: "输入问题，预览助手在这个资料库里能查到的内容。",
  previewPlaceholder: "试试输入一个问题…",
  previewEmpty: "没有查到相关内容。换个说法，或先添加更多资料。",
  previewInitial: "输入问题后回车，看看能查到什么。",
  previewRun: "查阅",
} as const;
