export const computerCopy = {
  featureName: "桌面操作",
  start: "开启桌面操作",
  startConfirmTitle: "允许 AI 操作你的电脑？",
  startConfirmBody: "开启后，AI 会自主点击、输入、操作你当前的屏幕来完成任务。你可以随时点「停止」中止。",
  stop: "停止",
  stopped: "已停止桌面操作",
  started: "已开启桌面操作",
  startFailed: "无法开启桌面操作",
  permTitle: "需要「辅助功能」权限",
  permBody: "桌面操作需要你在「系统设置 → 隐私与安全性 → 辅助功能」里允许本应用控制电脑。",
  permOpen: "去开启",
  permRecheck: "重新检测",
  emptyTitle: "尚未有桌面操作",
  emptyHint: "桌面操作已就绪，AI 需要时会自动在电脑上完成操作，过程会实时显示在这里。",
  loading: "正在准备桌面操作…",
  errorTitle: "桌面操作出错",
  retry: "重试",
  stepLook: "查看屏幕", stepClick: "点击", stepType: "输入",
  stepKey: "按键", stepScroll: "滚动", stepWait: "等待",
} as const;
